jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install Composer
        run: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
             php composer-setup.php
             php -r "unlink('composer-setup.php');"

      - name: Install Dependencies
        run: php composer.phar install

      - name: Wait for DB
        run: sleep 15

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit tests
